# Worlds & Levels..

[F]
id="F"
name="Flower Gardens"
music="flower-gardens"
special=["world"]
background="none"
tilemap = """
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  @ ..   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~        ~~~   ~~~   - ...       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~     --7--  ~  P ~~~ . -      ..   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~   ::: -   -     -  ~~ . 1---------    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~  6------ ~ ------8  ~~ . ::      :- .  ~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~   -                            ..  -   ~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~ --- ... H      ..   : 3------------2  ~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~ -    ...  :           -              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~ -:::             : ----    ~~~~~    ~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~  5-------------- .. -       ~~~~~~~~~~  :H   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~             :: -----4   ...  ~~~~~~~~~  .    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~     .....    -        ...      ~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~    ...    --H ~~~           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~            ~~~ H ::   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"""


[F-1]
world="F"
id=1
name="Typical Beginnings"

music="grassland"
special=[]
background="hills"
tilemap = """
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=------------------------------------------------------------------------==--------=
=------------------------------------------------------------------------==~~~======
=-----------------------------------------------------------------------------======
=--------------------------------------------------------------------------------===
=------------------------------------------------------------=========-------------=
=-----------------------------------------------------------===========------------=
=-----------------------------------------------------------===========---CC-------=
=------------------------------------------------------------===========-----------=
=-----------------------------------000-------------------------========-----------=
=----------------------------------0------------------------------======-----CCC---=
=----------000--------------------0--=========~~~~====xxx====-=-=-=====------------=
=------------------------------------======--------=========-----------------------=
=----------x??x----------------------====-----------=======---------------------PP-=
=----------------------------0---========------------======--00000000-----PP----PP-=
=-------------------------000---=========-G---------=======--00000000--PP-PP----PP-=
=---@->------------------------============================------------PP-PP-------=
=============================================================================------=
=============================================================================------=
=============================================================================------=
"""

[F-2]
world="F"
id=2
name="Debug Land"

music="athletic"
special=["floating"]
background="clouds"
tilemap = """
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=-------------------------------------------=
=---------------xxxxxx----------------------=
=----------------------------------x--x-----=
=------------------------x----x-------------=
=--------?---------------xxxxxxxxxxxxxx-----=
=-------------------------------x-----------=
=-------------------------------x-----------=
=-----xxxxxxxxx-------->--------x-----------=
=---------------------xxx*****xxx-----------=
=---------------xxxxxxx--------------$--$---=
=-------------------xxx--------------x##x---=
=----@-----$-------------------------xxxx---=
=--======================-----============--=
=--======================-----============--=
=--======================-----============--=
"""
